// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

interface ICampaignManager {
    function getCampaign(uint256 campaignId) external view returns (
        address advertiser,
        string memory adName,
        string memory videoUrl,
        uint256 rewardPerView,
        uint256 remainingBudget,
        bool active
    );

    function releaseReward(uint256 campaignId, address user) external;
}

contract AdInteraction {
    using ECDSA for bytes32;

    address public owner;
    address public verifier;
    ICampaignManager public immutable campaignManager;

    mapping(address => mapping(uint256 => bool)) public hasClaimed;

    event AdClaimed(address indexed user, uint256 indexed campaignId, uint256 reward);
    event VerifierUpdated(address indexed newVerifier);

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner");
        _;
    }

    constructor(address campaignManagerAddress, address _verifier) {
        require(campaignManagerAddress != address(0), "Invalid campaign manager");
        require(_verifier != address(0), "Invalid verifier");
        owner = msg.sender;
        verifier = _verifier;
        campaignManager = ICampaignManager(campaignManagerAddress);
    }

    function setVerifier(address _verifier) external onlyOwner {
        require(_verifier != address(0), "Invalid verifier");
        verifier = _verifier;
        emit VerifierUpdated(_verifier);
    }

    function claimReward(uint256 campaignId, bytes calldata signature) external {
        (
            address advertiser,
            ,
            ,
            uint256 rewardPerView,
            uint256 remainingBudget,
            bool active
        ) = campaignManager.getCampaign(campaignId);

        require(advertiser != address(0), "Invalid campaign");
        require(active, "Campaign inactive");
        require(msg.sender != advertiser, "Advertiser cannot claim");
        require(!hasClaimed[msg.sender][campaignId], "Already claimed");
        require(remainingBudget >= rewardPerView, "Budget exhausted");

        // Verify Proof-of-View signature generated by the backend
        bytes32 messageHash = keccak256(abi.encodePacked(msg.sender, campaignId));
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);
        
        address recoveredSigner = ECDSA.recover(ethSignedMessageHash, signature);
        require(recoveredSigner == verifier, "Invalid signature");

        hasClaimed[msg.sender][campaignId] = true;

        campaignManager.releaseReward(campaignId, msg.sender);

        emit AdClaimed(msg.sender, campaignId, rewardPerView);
    }
}
